[theme]
base = "dark"
primaryColor = "#1ed760"
backgroundColor = "#000000"
secondaryBackgroundColor = "#121212"
codeBackgroundColor = "#121212"
textColor = "#ffffff"
linkColor = "#4a9eff"
borderColor = "#7c7c7c"
showWidgetBorder = true
baseRadius = "0.3rem"
buttonRadius = "full"
font = "Poppins"
headingFontWeights = [600, 500, 500, 500, 500, 500]
headingFontSizes = ["3rem", "2.5rem", "2.25rem", "2rem", "1.5rem"]
chartCategoricalColors = ["#ffc862", "#2d46b9", "#b49bc8"]

[client]
toolbarMode = "minimal"

[theme.sidebar]
backgroundColor = "#000000"
secondaryBackgroundColor = "#000000"
codeBackgroundColor = "#000000"
borderColor = "#696969"

[server]
address = "0.0.0.0"
port = 8501
headless = true
